### ISSUE TITLE
Type 'ExecJarConfigure' property 'java' is missing an input or output annotation.

### ISSUE THREAD

**Issue by hanshnrch** [xcporter/jpkg#1]
Gradle 7.0 with Java 16 prints this error, when I run execJarConfig - task:
```
* What went wrong:
A problem was found with the configuration of task ':app:execJarConfig' (type 'ExecJarConfigure').
  - Type 'ExecJarConfigure' property 'java' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
```
I don't know wheter I can fix this problem in my `gradle.build` file or if your plugin needs to annotate the `java` var in line 21 of class `com.xcporter.jpkg.tasks.ExecJarConfigure` ?

**Comment by xcporter** [comment]
This is definitely an issue on my end--it looks like I'm not yet compatible with Gradle 7. 
I'll have a look at adding the proper annotations. 
In the meantime, if it's possible for your setup, using Gradle 6.x should keep keep your project moving.

**Comment by xcporter** [comment]
Ok--try it now with version 0.0.6, it should work with Gradle 7.0

```
plugins {
    id 'com.xcporter.jpkg' version '0.0.6'
}
```

**Comment by hanshnrch** [comment]
Thank you, 0.0.6 is working fine.
